### PR TITLE
Minor fixes in download in finalize tasks

### PR DESCRIPTION
**Pull request by zerwes**

### CODE REVIEW

**Comment by xshadow** [comment]
Hello @zerwes thanks, for this PR. I agree with the filemode but I do not see the necessity for the force option.  I needed this in any deployments before, could you explain why you think it is necessary and in which scenarios it helped you ?

**Comment by zerwes** [comment]
I agree, the force option for the symlink is somehow `me and myself` specific.
In my setup I usually have the roles:
  * configure apache (basic cfg w/out ssl)
  * create a ssl cert w/ cerbot
  * finish the apache config by enabling ssl
  * ...
  * nextcloud
 The first 3 require a domain name and a webroot in order to run.
For the sake of idem-potency I already use the webroot that later will be used by nextcloud:
```yaml
nextcloud_webroot: "{{ nextcloud_symlink }}"
```
And the playbooks will create the webroot if it is missing! So it is some kind of chicken-and-egg problem for the inital run only.
So from my point of view the nextcloud role should ensure the state as it is required by its own logic: a symlink.
Surely, I can a different webroot for the initial apache and certbot config or use a symlink to a inital directory too, but this would require the roles to have some knowledge of the logic and requirements in foreign roles. And I use the roles for other setups then nextcloud too. Or I could change the order, but from my point of view I prefer to have the roles in order of complexity.

**Conclusion:** If you think the force option is to dangerous, juts let me know and I will rebase the branch to the filemod changes only.
Greetings

**Comment by t2d** [comment]
Yes, force is to dangerous. I think some glue should take the responsibility of removing your old webroot.
The explicit mode looks fine though, thanks! Please rebase.

**Comment by zerwes** [comment]
The force part is now squashed out, juts the file modes in the download task remained.
Greetings

**Comment by xshadow** [comment]
Thank you

**Pull request merged**
